    
    <?php
    use yii\helpers\Html;
    use yii\widgets\ActiveForm;
    use yii\helpers\Url;
    use yii\helpers\ArrayHelper;
/** @var yii\web\View $this */
/** @var \app\models\Vacancies[] $vacancies */
/** @var \app\models\Applicants $applicant */
/** @var yii\widgets\ActiveForm $form */
?>

<br>
<br>
<br>
<br>
<section id="center" class="center_o bg_light pt-3 pb-3">
 <div class="container-xl">
  <div class="row center_o1">
   <div class="col-md-12">
	  <h6 class="mb-0 text-info"><a href="<?= Url::to(['/']); ?>"><?=Yii::t('app', 'Bosh sahifa')?></a> <span class="me-2 ms-2"><i class="bi bi-caret-right-fill align-middle text-muted"></i></span> <?= Html::encode($product->{"name_" . Yii::$app->language} ?? $product->name_en) ?></h6>
   </div>
  </div>
 </div>
</section>
    <div class="floating-particles">
        <!-- Particles will be generated by JavaScript -->
    </div>

    <div class="container">
        <div class="product-image">
            <div class="milk-carton">
                <div class="brand-overlay">RASH-MILK</div>
                <img src="<?= Yii::getAlias('@web/products/' . $product->image) ?>" 
                     alt="<?= $product->name_en?>" 
                     class="product-img">
            </div>
        </div>

        <div class="info-panel">
            <h1 class="title">
                <?= Html::encode($product->{"name_" . Yii::$app->language} ?? $product->name_en) ?>
            </h1>

            <div class="stats-grid">
                <div class="stat-card">
                    <div class="stat-icon">🥛</div>
                    <div class="stat-value"><?= Html::encode($product->oil) ?> g</div>
                    <div class="stat-label"><?= Yii::t('app', 'Yoglar') ?></div>
                </div>
                <div class="stat-card">
                    <div class="stat-icon">💪</div>
                    <div class="stat-value"><?= Html::encode($product->protein) ?> g</div>
                    <div class="stat-label"><?= Yii::t('app', 'Oqsillar') ?></div>
                </div>
                <div class="stat-card">
                    <div class="stat-icon">🌾</div>
                    <div class="stat-value"><?= Html::encode($product->carbohydrate) ?>g</div>
                    <div class="stat-label"><?= Yii::t('app', 'Uglevodlar') ?></div>
                </div>
                <div class="stat-card">
                    <div class="stat-icon">🔥</div>
                    <div class="stat-value"><?= Html::encode($product->energy) ?></div>
                    <div class="stat-label"><?= Yii::t('app', 'Kkal') ?></div>
                </div>
            </div>

            <div class="info-section">
                <div class="info-item">
                    <div class="info-icon">📏</div>
                    <div>
                        <strong><?= Yii::t('app', 'Sof massa') ?>:</strong> <?= Html::encode($product->weight) ?> g
                    </div>
                </div>
                <div class="info-item">
                    <div class="info-icon">⏰</div>
                    <div>
                        <strong><?= Yii::t('app', 'Saqlash muddati') ?>: </strong> <?= Html::encode($product->storage) ?> <?= Yii::t('app', 'kun') ?>
                    </div>
                </div>
                <div class="info-item">
                    <div class="info-icon">📦</div>
                    <div>
                        <strong><?= Yii::t('app', 'Qadoqdagi miqdori') ?>:</strong> <?= Html::encode($product->package) ?> <?= Yii::t('app', 'dona') ?>
                    </div>
                </div>
            </div>

            <div class="description">
                <?= Html::encode($product->{"description_" . Yii::$app->language} ?? $product->description_en) ?>
            </div>
        </div>
    </div>
    <?php
/* @var $this yii\web\View */

$this->registerJsFile(
    '@web/js/particle.js',
    ['depends' => [\yii\web\JqueryAsset::class]]
);
?>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- Owl Carousel CSS -->
<link rel="stylesheet" href=""/>
<link rel="stylesheet" href=""/>

<!-- Owl Carousel JS -->
<script src=""></script>

<div class="related-products mt-5">
    <h2 class="mb-4">&nbsp&nbsp&nbsp<?= Yii::t('app', 'Related products') ?></h2>
    <div class="owl-carousel owl-theme">
        <?php foreach ($relatedProducts as $rel): ?>
            <div class="item text-center p-3">
                <div class="card shadow-sm border-0">
                    <img src="<?= Yii::getAlias('@web/products/' . $rel->image) ?>"
                         class="card-img-top"
                         alt="<?= Html::encode($rel->{"name_" . Yii::$app->language}) ?>"
                         style="height: 200px; object-fit: contain;">
                    <div class="card-body">
                        <h5 class="card-title">
                            <?= Html::encode($rel->{"name_" . Yii::$app->language}) ?>
                        </h5>
                        <a href="<?= \yii\helpers\Url::to(['site/product-detail', 'id' => $rel->id]) ?>"
                           class="btn btn-primary btn-sm mt-2">
                            <?= Yii::t('app', 'Read more') ?>
                        </a>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>
<?php
$this->registerJs("
    $('.owl-carousel').owlCarousel({
        loop:true,
        margin:15,
        nav:true,
        dots:true,
        autoplay:true,
        autoplayTimeout:3000,
        responsive:{
            0:{ items:1 },
            600:{ items:2 },
            1000:{ items:4 }
        }
    });
");
?>

